#name : try {} catch {}
# --
try {
    $0
} catch (\Throwable $e) {
    printf('Caught exception : %s', $e->getMessage());
    throw $e;
}
